### PR TITLE
Snakemake corrections

### PR DESCRIPTION
**Pull request by 0xaf1f**
minor bugs in the workflow that would cause it to error out in some cases.

### CODE REVIEW

**Comment by 0xaf1f** [comment]
Thanks for merging. There's one more outstanding issue-- this code passes the same GATK jar file to both SomaticSeq and Mutect2, but SomaticSeq cannot work with GATK4. This problem would go away if you make that happen. Otherwise, it's probably necessary to have a `gatk3` config setting as well as a `gatk4` setting rather than just one for both. Do you think it's worth making this split now, or is an update to GATK4 in the SomaticSeq wrapper coming soon?

**Comment by lethalfang** [comment]
I'll see if I can switch out GATK3 to GATK4 (i.e., GATK3's CombineVariants
to GATK4's MergeVcfs).
Best,

**Comment by 0xaf1f** [comment]
That'd be great. Thanks!

**Comment by lethalfang** [comment]
Hi Afif,

I've been using GATK3's CombineVariants to merge VCF files. GATK4 doesn't
have its equivalent. I could switch out GATK3 CombineVariants, but that'll
probably take me a little while to do and then validate.
So for now, should I still merge your pull request?

Best,

**Comment by 0xaf1f** [comment]
#51? Well, I guess for now, it would break if anyone tried to run it as written, so maybe it's not a good idea to document it while it's known to be broken.

On the other hand, I saw that you did have support for running SomaticSeq without GATK at all, so maybe we should just not pass `--gatk` to the invocation of the SomaticSeq wrapper until GATK4 support there is ready. What do you think about that?

**Comment by lethalfang** [comment]
Yes, we can do that, not having --gatk argument at all.
Without --gatk, it'll just cat all the VCF and then sort using this command:

cat $all_snp | egrep -v '^#'  | awk -F "\t" '{print $1 "\t" $2 "\t.\t" $4
> "\t" $5}' | sort | uniq | awk -F "\t" '{print $1 "\t" $2 "\t" $3 "\t" $4
> "\t" $5 "\t" "." "\t" "PASS" "\t" "."}' | cat <(echo -e
> '##fileformat=VCFv4.1\n#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO') - |
> $MYDIR/utilities/vcfsorter.pl ${hg_dict} - >
> ${merged_dir}/CombineVariants_MVJSD.snp.vcf

**Comment by 0xaf1f** [comment]
Ok. I'll file an issue for this GATK4 thing just for tracking purposes, and then I'll add another commit to  #51.

**Pull request merged**
